### ISSUE TITLE
Build code without git history

### ISSUE THREAD

**Issue by RobustControl** [Simple-Robotics/proxsuite#104]
The Installation instructions in the official document use "git clone https://github.com/Simple-Robotics/proxsuite.git --recursive" to get the source code.

If I download the source code from releases directly (e.g. https://github.com/Simple-Robotics/proxsuite/archive/refs/tags/v0.2.7.tar.gz) and compile it, following error will be reported.
![image](https://user-images.githubusercontent.com/35950442/201323240-a5ea965b-49db-4cb3-af7d-1fdca3ec427c.png)

I think the main difference is that there is no git history for downloading source code from the releases.
How to solve this issue? 
Thank you!

**Comment by jcarpent** [comment]
Dear @RobustControl,

The issue comes from git, which does not compress the recursive modules within the zip archive.
This is why we provide a .tar.gz archive along with each release.
Please use this link https://github.com/Simple-Robotics/proxsuite/releases/download/v0.2.7/proxsuite-0.2.7.tar.gz

This is the way we proceed when deploying ProxSuite on conda or homebrew for instance.

**Comment by RobustControl** [comment]
> Dear @RobustControl,
> 
> The issue comes from GitHub, which does not compress the recursive modules within the zip archive. This is why we provide a .tar.gz archive along with each release. Please use this link https://github.com/Simple-Robotics/proxsuite/releases/download/v0.2.7/proxsuite-0.2.7.tar.gz
> 
> This is how we proceed when deploying ProxSuite on conda or homebrew for instance.

Thanks!
